server:
  port: 9000
  servlet:    context-path: /
spring:
  application:    name: provider-user  # 定义服务名称  datasource:
    #引入druid数据源
    type              : com.alibaba.druid.pool.DruidDataSource    driver-class-name : com.mysql.cj.jdbc.Driver
    url               : jdbc:mysql://server.net:3306/jtdb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username          : hwc
    password          : 123
#mybatis-plush配置
mybatis-plus:
  type-aliases-package: com.jt.springcloud.pojo
  mapper-locations    : classpath:/mybatis/mappers/*.xml
  configuration       :
    map-underscore-to-camel-case: true  #自动开启驼峰规则映射

# eureka服务提供者配置
eureka:  client:    service-url:      defaultZone: http://localhost:7000/eureka    # 配置注册中心地址
  instance:
    instance-id: provider-user-9000                # 定义微服务的名称
    prefer-ip-address: true                        # 是否显示IP和端口
    
  
  